### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearth1an.Intervention#1]
- [ ] Better ambience, music on Faith
- [ ] Faith texturing and grass, trees, structures. Change rotating rings to rotating glowing writings (like in Lord of the Rings lol)
- [ ] Add Hope planet and put Faith as it's orbit (basically owlks favorite ring planet)
- [x] Add some code to spawn and disable things (Ending for example)
- [x] Text improvements
- [x] Add translations
- [x] Fix supernova!
- [ ] Make trailer for YT

**Comment by hearth1an** [comment]
Not sure will do all this
